### ISSUE TITLE
single copy core genes

### ISSUE THREAD

**Issue by alantsangmb** [neherlab/pan-genome-analysis#15]
Hello Prof. Richard Neher @rneher 

If I want to obtain all single-copy genes that are present in all the studying genomes, which alignment files should I use? (given that I use the default 1.0 for the -cg parameter)

Are all the GC*_na_aln.fa under the /vis/geneCluster directory single-copy genes? I noticed that some aln filenames include a serial no. like GC*_x_na_aln.fa, where x=1,2,3,etc. Does it mean this gene is more than one copy in the genome?

I ask because I would like to obtain only the single-copy genes alignment and concatenate into a single super alignment or infer a supertree from each single gene tree ultimately.

Thank you.

**Comment by rneher** [comment]
for the species on the public page, we have assembled core genome alignments, e.g.:
http://pangenome.de/dataset/Bacillus_subtilis/core_gene_alignments.tar.gz

if you run your own analysis, you can filter for single copy core genes by going through the gene cluster json. Each gene cluster has an entry locus which lists all instances of the gene. If the length of this list equals the number of strains and the field `dupli` equals `no`, it is a core gene.

http://pangenome.de/dataset/Bacillus_subtilis/geneCluster.json

I hope this helps.

richard

**Comment by rneher** [comment]
yes, GC00000002_7_p1 and GC00000002_7_p2 would be paralogs. 
if there are multiple copies of one gene in a genome, they might be split into different paralogs or be present as recent duplication within a gene cluster. This depends on the parameters of the paralog splitting routine.

The core genome SNP tree should be only single copy core genes, hence SNPs in duplicated genes don't contribute.

**Comment by alantsangmb** [comment]
I got it, thanks!
