### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pneumowidow** [neherlab/pan-genome-analysis#17]
Hello,

I recently tried to run panX.py but I've been getting a Segmentation fault error. I installed all the dependencies via conda as suggested and then tried to run the test script. Instead, I got the error message below:

![image](https://user-images.githubusercontent.com/43600124/52744365-d4bd5800-2fdc-11e9-9bba-8156ce15e5de.png)

I'm not so sure what the problem is...maybe something with the python script? Really hope you can help.

Many thanks in advance

**Comment by pneumowidow** [comment]
A little update. I realized that maybe it had to do with the threads being 64..since the remote server I use has 20, I just removed the threads option in general and I still got the same segmentation fault problem

**Comment by rneher** [comment]
I need more information here. What step did it fail at? 

I don't think this is something in panX proper, but something involving external binaries that are called.

**Comment by pneumowidow** [comment]
It failed when I tried to run-Testser.sh. I also tried to run the help command with panX.py `./panX.py -h` but I still got the same "Segmentation fault" error

**Comment by rneher** [comment]
this suggests there is an issue with your python installation.

**Comment by pneumowidow** [comment]
@rneher you're right. My normal "base" conda env runs on python version 2.7.15, so I just changed the python version in the yml script to that and renamed the env and it works now. Thank you.
