### ISSUE TITLE
long_split issue

### ISSUE THREAD

**Issue by jpaganini** [neherlab/pan-genome-analysis#21]
Hi there, how r u? I'm getting an error while trying to run the script for comparing three genomes. I'm runnning the  following code:
`./panX.py -cg 0.66 -fn data/AbSputum -sl "Acinetobacter baumannii Sputum Isolates"`
 (I'm using -cg 0.66 because apparently the genomes are a bit diverse)

#times of splitting long branches: -1
Traceback (most recent call last):
  File "./panX.py", line 287, in <module>
    myPangenome.process_clusters()
  File "/home/julian/pan-genome-analysis/scripts/pangenome_computation.py", line 185, in process_clusters
    myClusterCollector.postprocessing_split_long_branch()
  File "/home/julian/pan-genome-analysis/scripts/cluster_collective_processing.py", line 25, in postprocessing_split_long_branch
    postprocess_split_long_branch(self.threads, self.path, self.simple_tree, self.split_long_branch_cutoff)
  File "/home/julian/pan-genome-analysis/scripts/sf_split_long_branch.py", line 294, in postprocess_split_long_branch
    with open(file_path+'old_clusters_longSplit.txt', 'rb') as delete_cluster_file:
IOError: [Errno 2] No such file or directory: '/home/julian/pan-genome-analysis/data/AbSputum/geneCluster/old_clusters_longSplit.txt'

any idea how can i fix this? Thanks in advanced for any help you can provide to me!

**Comment by rneher** [comment]
a little difficult to diagnose. What is the content of the geneCluster folder? what is the last step that completed successfully? (should be in the log file).

**Comment by jpaganini** [comment]
Dear Robert:

Thx a lot for your prompt response.\

1- the gene cluster folder contains the .faa, .fna, .nwk and tree.json files for each cluster

2- I belive that the last step completed succesfully was step 5. After that, I'm seeing the following code format many times...
 home/julian/miniconda2/envs/panX/bin/mafft: line 2561: popd: /home/julian/pan-genome-analysis/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040320_1517745/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040320_6215855/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040320_44506597/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040320_46725149/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_21671177/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_31356876/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_76390631/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_84906540/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_66029535/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_53457828/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_5702704/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040321_81314448/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_39462928/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_5356589/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_6807002/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_11901072/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_75997965/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_97354732/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_53659224/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_43857626/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040322_71330248/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_6976824/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_69454900/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_98214923/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_10338940/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_93028980/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_32622986/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_12573224/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_45457854/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040323_30132641/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_66538382/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_57713518/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_24707985/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_39559168/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_87959867/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_28404770/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_14456659/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_6160992/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_11487549/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040324_11326008/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_71223411/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_52082208/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_74846057/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_45887769/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_22838739/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_23241156/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_15069516/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_17947493/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_15560342/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040325_10242733/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_32485247/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_45823722/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_85905608/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_29009731/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_28617899/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_27204994/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_2380389/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_31162236/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040326_90897495/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_61059490/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_99979092/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_14609174/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_13494611/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_48763374/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_93478808/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_86259579/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_86634131/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040327_38876606/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_14707435/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_58114370/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_38495681/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_14380274/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_23990091/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_50006441/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_56877185/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_15312296/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040328_58917662/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_18736256/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_78609445/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_72307333/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_90763684/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_86151089/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_11803893/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_20046504/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_16388236/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040329_42662043/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_60680573/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_5527653/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_25620860/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_69980013/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_66707013/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_58803308/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_65141288/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040330_88030138/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_13356984/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_5709843/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_60505126/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_82871177/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_57393785/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_85363676/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_12312205/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_38860693/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040331_29084382/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_88524281/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_81151429/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_78337851/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_58851012/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_54555502/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_91799630/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_92111661/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040332_97934804/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_90566413/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_49203662/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_16497997/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_85965839/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_97455783/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_58116359/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_50411031/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_19985529/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040333_24141032/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_94103508/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_93089802/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_22408712/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_9049221/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_56431678/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_70160566/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_78022886/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040334_8333179/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_75883049/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_87838914/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_56538262/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_42322457/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_51859557/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_5886071/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_2058000/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040335_45181959/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_7310397/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_66738502/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_58055298/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_61000673/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_65447543/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_48155964/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_53922697/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_49074617/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040336_79872327/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_49517847/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_13923174/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_43345419/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_55794844/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_26240771/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_74641591/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_49105274/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040337_89413746/tmp/Acinetobacter baumannii Sputum
 Isolates_tmp_040338_73673327/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_51240944/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_79570562/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_97245960/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_18859767/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_80837414/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_55791820/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040338_41299381/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_25114587/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_57358184/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_30570659/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_37949101/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_25848685/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_23163437/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_26904640/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040339_76349126/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_6831985/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_48767031/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_71547531/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_8238455/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_16258738/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_42502705/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040340_60378711/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_37656592/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_51339188/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_15731459/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_71229594/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_80032022/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_42918026/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_35947456/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040341_1386536/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_94183461/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_66038505/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_46997419/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_94147909/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_98385266/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_44660479/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_85509381/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040342_88830178/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_83467386/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_43674562/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_47714902/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_35203595/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_19132297/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_60882398/tmp/Acinetobacter baumannii Sputum Isolates_tmp_040343_41041051: File name too long
('problem in sequence diversity calculation:', '/home/julian/pan-genome-analysis/data/AbSputum/protein_faa/diamond_matches/tmp_core/GC00000064.fna')
/home/julian/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/julian/.local/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
factor used: 2.0
average core genome diversity: nan
defined core genome diversity cutoff for splitting long branches: nan
Process Process-2:
Traceback (most recent call last):
  File "/home/julian/miniconda2/envs/panX/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/julian/miniconda2/envs/panX/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/julian/pan-genome-analysis/scripts/sf_geneCluster_align_makeTree.py", line 609, in create_geneCluster_fa
    geneSeqID=geneID_to_geneSeqID_dict[gene_memb]
KeyError: 'CP015364'
nthread = 0
nthreadpair = 0
nthreadtb = 0
ppenalty_ex = 0
stacksize: 8192 kb
Gap Penalty = -1.53, +0.00, +0.00

and finally, what I previously posted.

Let me know if this helps please.

Thanks again for your time.

**Comment by rneher** [comment]
It looks as if there is some issue with filenames. I don't think this "File name too long" error is by panX.

richard

**Comment by jpaganini** [comment]
Richard, thanks a lot. I changed the names of the files and the software got thru that step.

**Comment by faraziAnindo** [comment]
i am facing same kind of problem can you please help me in this matter @jpaganini @rneher 



IOError: [Errno 2] No such file or directory: '/home/a/Desktop/pan-genome-analysis/data/protein_faa/diamond_matches/allclusters.tsv'
