### ISSUE TITLE
pan genome visualization component "Sequence Alignment" not working

### ISSUE THREAD

**Issue by wshropshire** [neherlab/pan-genome-analysis#22]
Hello, 

I have had an issue both when viewing the panX Test Set as well as my own Test Set where the Sequence Alignment visualization component doesn't appear in FireFox. I was wondering if you knew if there was a particular npm module that after updating might be breaking one of your java script functions and if so, which module I need to version control for. Here is a screen shot of the issue:

<img width="1264" alt="Screen Shot 2019-03-28 at 11 38 25 AM" src="https://user-images.githubusercontent.com/34726302/55176200-b22b6c80-514e-11e9-82ce-db9cf94c9edf.png">

And here are all of the NodeJS/npm dependencies currently downloaded on my Mac.

<img width="508" alt="Screen Shot 2019-03-28 at 11 46 11 AM" src="https://user-images.githubusercontent.com/34726302/55176558-56adae80-514f-11e9-8886-33744191e269.png">
<img width="304" alt="Screen Shot 2019-03-28 at 11 46 25 AM" src="https://user-images.githubusercontent.com/34726302/55176576-5f05e980-514f-11e9-9805-fc4c922ae1c8.png">
<img width="337" alt="Screen Shot 2019-03-28 at 11 46 33 AM" src="https://user-images.githubusercontent.com/34726302/55176609-6e853280-514f-11e9-9460-b1158f06c14a.png">
 
Thank you so much for your wonderful pan-genome visualization tool!

**Comment by rneher** [comment]
I am not aware of any incompatibility. the MSA viewer is part of the git repo. Does it work on other browsers? Do you get any errors in the browser console?

thanks,
richard

**Comment by wshropshire** [comment]
Hey Richard, 

Sorry I tested it on Chrome/Safari and they both work, just not Firefox. When I previously used this tool in November, I had issues with it working on Chrome, but maybe after updating NodeJS packages, it fixed whatever data visualization incompatibility was there. Thanks for your quick reply!
