### ISSUE TITLE
How strain file should be formatted?

### ISSUE THREAD

**Issue by FilipeMatteoli** [neherlab/pan-genome-analysis#29]
I have prepared the file as:
GCF_000010725.1
GCF_000237365.1
GCF_000283655.1
...

Whenever I run step 1 and 3, get:
======  step01: strain list successfully loaded
======  starting step03: extract sequences from GenBank file
======  time for step03:
 0.00 minutes (0.01 seconds) 

But .data/strain_name/input_gbk remains emptyy

I am running as follows:
./panX.py -fn ./data/Azospirillum_sp/ -sl Azospirillum_sp -st 1 2 3 -t 10

Am I missing something?

**Comment by FilipeMatteoli** [comment]
Well, I figured it out. In general, I believe that the documentation can be improved.

Turns out that the user cannot provide a strain list file, panX creates it from the directory based on the gbk sequences within it.

**Comment by rneher** [comment]
yes, we are aware that the docs aren't up to standards. glad you figured it out.
