### ISSUE TITLE
The meaning of file name in geneCluster directory

### ISSUE THREAD

**Issue by kaiher** [neherlab/pan-genome-analysis#6]
I used panX for pan genome analysis (v1.5.1) on ubuntu (18.04.1 LTS). 

I would like to know the meaning of file names in geneCluster directory in my result. In this directory, I found many faa and fsa files for each genecluster. Some files had additonal number or character after the name of gene cluster (GCxxxxxxxx_x, px or rx; x indicated a number) in their file names. I wonder that the number meant the serial number for distantly related genes split in the post processing step, and "p+number" did those for paralogous genes. But what did "r + number" mean? 

Kind regards,

**Comment by rneher** [comment]
You are correct. These are names that get generated in successive rounds of paralog splitting or long-branch splitting. the `_rx` is here simply the part that remains after splitting. no particularly deep meaning.
